#!/usr/bin/env python3
# Copyright 2024 Bytedance Ltd. and/or its affiliates
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""Compare iid GRPO sampling with three tree-decoding trigger policies.

Every method contributes exactly ``n`` complete answer candidates per prompt.
A tree contributes its complete leaves; any remaining slots are generated by
ordinary iid sampling. Internal tree nodes are segments, not pass@k candidates.
"""

from __future__ import annotations

# Enable unbuffered output for better debugging
import os
os.environ['PYTHONUNBUFFERED'] = '1'

import argparse
import json
import math
import sys
import time
import uuid
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

import numpy as np
import pandas as pd
from tqdm import tqdm

# Prefer the explicitly selected source checkout over an installed vLLM. The
# shell wrapper exports this path; the default matches this workspace.
VLLM_SOURCE_PATH = os.environ.get(
    "VLLM_SOURCE_PATH", "/Users/bytedance/codes/vllm")
if VLLM_SOURCE_PATH:
    sys.path.insert(0, VLLM_SOURCE_PATH)

try:
    import vllm
    from vllm import LLM, SamplingParams
    from vllm.sampling_params import TreeSearchParams
    VLLM_AVAILABLE = True
    VLLM_IMPORT_ERROR = None
except ImportError as exc:
    VLLM_AVAILABLE = False
    VLLM_IMPORT_ERROR = exc
    print(f"Warning: vllm not available: {exc}")


METHOD_LABELS = {
    "base_grpo": "Base GRPO",
    "random_tree": "Random tree",
    "entropy_only_tree": "Entropy-only tree",
    "entropy_waad_tree": "Entropy+WAAD tree",
}


@dataclass
class MathExample:
    """Data class for a math problem example."""
    problem: str
    ground_truth: str
    prompt: str
    idx: int


def load_dapo_math_dataset(dataset_path: str) -> pd.DataFrame:
    """
    Load dapo-math dataset from parquet file.

    Args:
        dataset_path: Path to dapo-math-17k.parquet

    Returns:
        DataFrame with dataset
    """
    import pyarrow.parquet as pq
    table = pq.read_table(dataset_path)
    df = table.to_pandas()
    print(f"Loaded dataset with {len(df)} rows")
    return df


def extract_unique_queries_streaming(dataset_path: str, num_samples: int = 500) -> List[MathExample]:
    """
    Extract unique queries from dataset using streaming, stop when enough samples are collected.

    Args:
        dataset_path: Path to dapo-math-17k.parquet
        num_samples: Number of unique samples to extract

    Returns:
        List of MathExample objects
    """
    import pyarrow.parquet as pq

    print(f"Starting streaming read from: {dataset_path}")
    print(f"Target: collect {num_samples} unique samples")

    seen_prompts = set()
    examples = []
    rows_processed = 0
    batches_processed = 0

    # Open the parquet file for streaming
    parquet_file = pq.ParquetFile(dataset_path)
    print(f"Total number of row groups: {parquet_file.num_row_groups}")
    print(f"Total number of rows: {parquet_file.metadata.num_rows}")

    for batch_idx in range(parquet_file.num_row_groups):
        batches_processed += 1
        if batches_processed % 10 == 0:
            print(f"  Read {batches_processed}/{parquet_file.num_row_groups} batches, "
                  f"{rows_processed} rows, {len(examples)}/{num_samples} unique samples")

        # Read one row group
        table = parquet_file.read_row_group(batch_idx)
        df = table.to_pandas()
        rows_processed += len(df)

        # Process each row in the batch
        for _, row in df.iterrows():
            if len(examples) >= num_samples:
                break

            # Determine which column to use for deduplication
            prompt_key = None
            prompt_text = None
            ground_truth = None
            problem = None

            if 'prompt' in df.columns and 'reward_model' in df.columns:
                # Format from verl's preprocessed data
                prompt = row['prompt']
                if isinstance(prompt, list) and len(prompt) > 0:
                    prompt_text = prompt[0].get('content', '')
                else:
                    prompt_text = str(prompt)
                ground_truth = row.get('reward_model', {}).get('ground_truth', '')
                problem = prompt_text
                prompt_key = prompt_text

            elif 'problem' in df.columns and 'solution' in df.columns:
                # Original MATH dataset format
                problem = row['problem']
                solution = row['solution']
                ground_truth = extract_answer_from_solution(solution)
                # Add instruction following prompt
                prompt_text = problem + " Let's think step by step and output the final answer within \\boxed{}."
                prompt_key = problem

            else:
                # Try to infer from columns
                problem = str(row.iloc[0])
                prompt_text = problem
                ground_truth = str(row.iloc[1]) if len(row) > 1 else ''
                prompt_key = problem

            # Skip if we've seen this prompt before
            if prompt_key in seen_prompts:
                continue

            # Add to collection
            seen_prompts.add(prompt_key)
            examples.append(MathExample(
                problem=problem,
                ground_truth=ground_truth,
                prompt=prompt_text,
                idx=len(examples)
            ))

        if len(examples) >= num_samples:
            print(f"  ✓ Collected enough samples, stopping early!")
            break

    print(f"\nDone! Processed {rows_processed} rows from {batches_processed} batches")
    print(f"Extracted {len(examples)} unique examples")

    return examples


def extract_unique_queries(df: pd.DataFrame, num_samples: int = 500) -> List[MathExample]:
    """
    Extract unique queries from dataset (in-memory version).
    Kept for backward compatibility, prefer extract_unique_queries_streaming.

    Args:
        df: Input dataframe
        num_samples: Number of unique samples to extract

    Returns:
        List of MathExample objects
    """
    # Find unique problems
    if 'prompt' in df.columns:
        # Try to extract problem from prompt
        unique_df = df.drop_duplicates(subset=['prompt'])
    elif 'problem' in df.columns:
        unique_df = df.drop_duplicates(subset=['problem'])
    else:
        # Assume first column is the problem
        unique_df = df.drop_duplicates()

    print(f"Found {len(unique_df)} unique problems")

    # Sample if needed
    if len(unique_df) > num_samples:
        unique_df = unique_df.sample(n=num_samples, random_state=42)

    examples = []
    for idx, row in unique_df.iterrows():
        # Extract problem and ground truth based on available columns
        if 'prompt' in df.columns and 'reward_model' in df.columns:
            # Format from verl's preprocessed data
            prompt = row['prompt']
            if isinstance(prompt, list) and len(prompt) > 0:
                prompt_text = prompt[0].get('content', '')
            else:
                prompt_text = str(prompt)
            ground_truth = row.get('reward_model', {}).get('ground_truth', '')
            problem = prompt_text
        elif 'problem' in df.columns and 'solution' in df.columns:
            # Original MATH dataset format
            problem = row['problem']
            solution = row['solution']
            ground_truth = extract_answer_from_solution(solution)
            # Add instruction following prompt
            prompt_text = problem + " Let's think step by step and output the final answer within \\boxed{}."
        else:
            # Try to infer from columns
            problem = str(row.iloc[0])
            prompt_text = problem
            ground_truth = str(row.iloc[1]) if len(row) > 1 else ''

        examples.append(MathExample(
            problem=problem,
            ground_truth=ground_truth,
            prompt=prompt_text,
            idx=len(examples)
        ))

    print(f"Extracted {len(examples)} unique examples")
    return examples


def extract_answer_from_solution(solution: str) -> str:
    """Extract boxed answer from solution string."""
    try:
        idx = solution.rfind("\\boxed")
        if idx < 0:
            idx = solution.rfind("\\fbox")
            if idx < 0:
                return solution.strip()

        i = idx
        right_brace_idx = None
        num_left_braces_open = 0
        while i < len(solution):
            if solution[i] == "{":
                num_left_braces_open += 1
            if solution[i] == "}":
                num_left_braces_open -= 1
                if num_left_braces_open == 0:
                    right_brace_idx = i
                    break
            i += 1

        if right_brace_idx is None:
            return solution.strip()
        return solution[idx:right_brace_idx + 1].replace("\\boxed", "").replace("\\fbox", "").strip("{}")
    except Exception:
        return solution.strip()


# ========== Math Grading Functions ==========
# These are adapted from verl's math_reward module


def last_boxed_only_string(string: str) -> Optional[str]:
    """Extract last boxed content from string."""
    idx = string.rfind("\\boxed")
    if idx < 0:
        idx = string.rfind("\\fbox")
        if idx < 0:
            return None

    i = idx
    right_brace_idx = None
    num_left_braces_open = 0
    while i < len(string):
        if string[i] == "{":
            num_left_braces_open += 1
        if string[i] == "}":
            num_left_braces_open -= 1
            if num_left_braces_open == 0:
                right_brace_idx = i
                break
        i += 1
    if right_brace_idx is None:
        return None
    return string[idx:right_brace_idx + 1]


def remove_boxed(s: str) -> str:
    """Remove boxed wrapper from string."""
    left = "\\boxed{"
    try:
        if s[:len(left)] == left and s[-1] == "}":
            return s[len(left):-1]
    except Exception:
        pass
    return s


def extract_answer(generation: str) -> Optional[str]:
    """Extract answer from generation."""
    if "\\boxed" in generation or "\\fbox" in generation:
        boxed = last_boxed_only_string(generation)
        if boxed:
            return remove_boxed(boxed)
    return None


def normalize_answer(answer: Optional[str]) -> Optional[str]:
    """Normalize answer for comparison."""
    if answer is None:
        return None
    answer = answer.strip()

    # Remove units and common patterns
    import re
    answer = re.sub(r'\\text\{.*?\}$', '', answer).strip()
    answer = re.sub(r'\\text\{', '', answer)
    answer = answer.replace('}', '')
    answer = answer.replace('{', '')
    answer = answer.replace('$', '')

    # Try to extract numerical value
    try:
        # Check if it's a number
        val = float(answer.replace(',', ''))
        if val.is_integer():
            return str(int(val))
        return str(val)
    except (ValueError, TypeError):
        pass

    return answer


def grade_answer(model_answer: Optional[str], ground_truth: str) -> bool:
    """
    Grade if model answer matches ground truth.

    Args:
        model_answer: Extracted answer from model
        ground_truth: Ground truth answer

    Returns:
        True if correct, False otherwise
    """
    if model_answer is None:
        return False

    # Normalize both answers
    norm_model = normalize_answer(model_answer)
    norm_gt = normalize_answer(ground_truth)

    if norm_model is None or norm_gt is None:
        return False

    # Direct string match
    if norm_model == norm_gt:
        return True

    # Try numerical comparison
    try:
        model_val = float(norm_model.replace(',', ''))
        gt_val = float(norm_gt.replace(',', ''))
        if abs(model_val - gt_val) < 1e-4:
            return True
    except (ValueError, TypeError):
        pass

    # Try symbolic comparison as fallback
    try:
        import sympy
        model_expr = sympy.sympify(norm_model)
        gt_expr = sympy.sympify(norm_gt)
        if sympy.simplify(model_expr - gt_expr) == 0:
            return True
    except Exception:
        pass

    return False


def evaluate_generations(generations: List[str], ground_truth: str) -> List[bool]:
    """
    Evaluate a list of generations against ground truth.

    Args:
        generations: List of generated responses
        ground_truth: Ground truth answer

    Returns:
        List of booleans indicating correctness
    """
    results = []
    for gen in generations:
        answer = extract_answer(gen)
        correct = grade_answer(answer, ground_truth)
        results.append(correct)
    return results


# ========== Threshold Calibration ==========

def collect_threshold_stats(
    llm: LLM,
    prompts: List[str],
    n: int = 5,
    temperature: float = 1.0,
    top_p: float = 1.0,
    top_k: int = -1,
    max_tokens: int = 200,
    quantile: float = 0.8,
    seed: Optional[int] = None,
) -> Tuple[float, float]:
    """
    Collect entropy and importance stats using vllm's collect_threshold_stats mode,
    then compute quantiles as thresholds.

    Args:
        llm: vLLM instance
        prompts: List of prompts for calibration
        n: Number of sequences per prompt for calibration
        temperature: Sampling temperature
        top_p: Top-p sampling parameter
        top_k: Top-k sampling parameter
        max_tokens: Max tokens for calibration (shorter than full generation)
        quantile: Quantile to use for threshold (0.8 = 80th percentile)

    Returns:
        Tuple of (entropy_threshold, tau_importance)
    """
    print("\nCollecting threshold stats...")

    all_entropies = []
    all_importances = []

    params = [
        SamplingParams(
            n=n,
            temperature=temperature,
            top_p=top_p,
            top_k=top_k,
            max_tokens=max_tokens,
            collect_threshold_stats=True,
            # The training path is entropy-only. This comparison utility opts
            # in explicitly because it still benchmarks the legacy WAAD mode.
            collect_importance_stats=True,
            seed=None if seed is None else seed + prompt_idx * n,
        )
        for prompt_idx in range(len(prompts))
    ]

    # Process prompts in one batch
    outputs = llm.generate(prompts, params)

    for output in outputs:
        for i in range(len(output.outputs)):
            result = output.outputs[i]
            if hasattr(result, 'entropy_list') and result.entropy_list:
                all_entropies.extend(result.entropy_list)
            if hasattr(result, 'importance_list') and result.importance_list:
                all_importances.extend([x for x in result.importance_list if x is not None])

    if not all_entropies or not all_importances:
        raise RuntimeError(
            "Threshold calibration did not return both entropy and WAAD "
            f"statistics (entropy={len(all_entropies)}, "
            f"waad={len(all_importances)}). Entropy+WAAD would otherwise run "
            "with a misleading fallback threshold. Ensure the custom vLLM "
            "checkout is loaded and chunked prefill is disabled.")

    entropy_threshold = float(np.quantile(all_entropies, quantile))
    tau_importance = float(np.quantile(all_importances, quantile))
    print(f"  Entropy stats: {len(all_entropies)} tokens")
    print(f"  Entropy range: [{min(all_entropies):.4f}, {max(all_entropies):.4f}]")
    print(f"  Entropy {int(quantile*100)}th percentile: {entropy_threshold:.4f}")
    print(f"  Importance stats: {len(all_importances)} tokens")
    print(f"  Importance range: [{min(all_importances):.4f}, {max(all_importances):.4f}]")
    print(f"  Importance {int(quantile*100)}th percentile: {tau_importance:.4f}")

    return entropy_threshold, tau_importance


# ========== Pass@k Calculation ==========

def compute_pass_at_k(results_per_example: List[List[bool]], k: int) -> float:
    """Compute the order-invariant pass@k candidate-pool estimator.

    For one prompt with ``n`` observed candidates and ``c`` correct answers,
    the score is ``1 - C(n-c, k) / C(n, k)``. For correlated tree leaves this
    should be read as the success probability of a uniformly chosen k-subset
    of the observed pool, rather than as an iid-policy estimator.

    Args:
        results_per_example: List where each element is a list of booleans
                            indicating correctness for that example's generations
        k: k for pass@k

    Returns:
        pass@k score
    """
    if k < 1:
        raise ValueError(f"k must be positive, got {k}.")
    if not results_per_example:
        raise ValueError("pass@k requires at least one example.")

    scores = []

    for example_idx, results in enumerate(results_per_example):
        if len(results) == 0:
            raise ValueError(
                f"Example {example_idx} has no candidates; pass@k cannot "
                "silently exclude it from the denominator.")
        n = len(results)
        if k > n:
            raise ValueError(
                f"pass@{k} requires at least {k} candidates, got {n}.")
        c = sum(bool(value) for value in results)
        miss_probability = (
            0.0 if n - c < k
            else math.comb(n - c, k) / math.comb(n, k)
        )
        scores.append(1.0 - miss_probability)

    return float(np.mean(scores)) if scores else 0.0


def compute_all_pass_k(results_per_example: List[List[bool]], max_k: int = 8) -> Dict[str, float]:
    """
    Compute pass@1 to pass@max_k.

    Args:
        results_per_example: List where each element is a list of booleans
        max_k: Maximum k to compute

    Returns:
        Dictionary with pass@k scores
    """
    pass_k_scores = {}
    for k in range(1, max_k + 1):
        pass_k_scores[f"pass@{k}"] = compute_pass_at_k(results_per_example, k)
    return pass_k_scores


# ========== Generation with vLLM ==========

def generate_base_grpo(
    llm: LLM,
    prompts: List[str],
    n: int = 8,
    temperature: float = 1.0,
    top_p: float = 1.0,
    top_k: int = -1,
    max_tokens: int = 4096,
    seed: Optional[int] = None,
) -> List[List[str]]:
    """
    Generate using base GRPO sampling (independent sampling).

    Default parameters match verl's RolloutConfig:
    - temperature: 1.0
    - top_p: 1.0
    - top_k: -1

    Args:
        llm: vLLM instance
        prompts: List of prompts
        n: Number of sequences per prompt
        temperature: Sampling temperature
        top_p: Top-p sampling parameter
        top_k: Top-k sampling parameter
        max_tokens: Max tokens to generate

    Returns:
        List where each element is a list of n generations for that prompt
    """
    sampling_params = [
        SamplingParams(
            temperature=temperature,
            max_tokens=max_tokens,
            n=n,
            top_p=top_p,
            top_k=top_k,
            seed=None if seed is None else seed + prompt_idx * n,
        )
        for prompt_idx in range(len(prompts))
    ]

    outputs = llm.generate(prompts, sampling_params)
    if len(outputs) != len(prompts):
        raise RuntimeError(
            f"Base GRPO returned {len(outputs)} prompt outputs for "
            f"{len(prompts)} prompts.")

    all_generations = []
    for prompt_idx, output in enumerate(outputs):
        gens = [o.text if o.text is not None else "" for o in output.outputs]
        if len(gens) != n:
            raise RuntimeError(
                f"Base GRPO prompt {prompt_idx} returned {len(gens)} "
                f"candidates; expected exactly {n}.")
        all_generations.append(gens)

    return all_generations


def reconstruct_tree_leaf_text(leaf: Any, seq_map: Dict[int, Any]) -> str:
    """Reconstruct one complete leaf response without discarding empty text."""
    path_texts = []
    current = leaf
    visited = set()

    while current is not None:
        seq_id = getattr(current, "seq_id", None)
        if seq_id is not None:
            if seq_id in visited:
                raise RuntimeError(f"Cycle found in tree output at seq_id={seq_id}.")
            visited.add(seq_id)

        segment = getattr(current, "tree_text", None)
        if segment is None:
            segment = getattr(current, "text", "")
        path_texts.append(segment or "")

        parent_seq_id = getattr(current, "parent_seq_id", None)
        if parent_seq_id is None:
            current = None
        elif parent_seq_id not in seq_map:
            raise RuntimeError(
                f"Tree leaf seq_id={getattr(leaf, 'seq_id', None)} refers "
                f"to missing parent_seq_id={parent_seq_id}.")
        else:
            current = seq_map[parent_seq_id]

    return "".join(reversed(path_texts))


def extract_tree_leaf_candidates(output: Any) -> Tuple[List[str], Dict[str, int]]:
    """Extract complete leaves and tree-shape metadata from one output."""
    nodes = list(output.outputs)
    seq_map = {}
    for node in nodes:
        seq_id = getattr(node, "seq_id", None)
        if seq_id is None:
            continue
        if seq_id in seq_map:
            raise RuntimeError(f"Duplicate seq_id={seq_id} in tree output.")
        seq_map[seq_id] = node
    leaf_nodes = [node for node in nodes if getattr(node, "is_leaf", None) is True]
    if not leaf_nodes:
        raise RuntimeError(
            "Tree decoding returned no nodes marked is_leaf=True. Verify that "
            f"the custom vLLM checkout is loaded from {VLLM_SOURCE_PATH!r}.")

    candidates = [
        reconstruct_tree_leaf_text(leaf, seq_map) for leaf in leaf_nodes
    ]
    shape = {
        "tree_leaf_count": len(leaf_nodes),
        "tree_internal_node_count": sum(
            getattr(node, "is_leaf", None) is False for node in nodes),
        "tree_output_node_count": len(nodes),
    }
    return candidates, shape


def generate_tree_decoding(
    llm: LLM,
    prompts: List[str],
    branch_trigger_mode: str,
    target_n: int,
    branching_factor: int = 2,
    max_tree_depth: int = 3,
    entropy_threshold: float = 1.0,
    tau_importance: Optional[float] = None,
    random_branch_probability: float = 0.2,
    min_seg_length: int = 128,
    temperature: float = 1.0,
    top_p: float = 1.0,
    top_k: int = -1,
    max_tokens: int = 4096,
    seed: Optional[int] = None,
) -> Tuple[List[List[str]], List[Dict[str, Any]]]:
    """
    Generate using Tree Decoding.

    The tree is capped at ``target_n`` complete leaves. If it produces fewer,
    the deficit is filled with fresh iid GRPO samples using identical sampling
    parameters. Duplicate and empty responses each consume one candidate slot.

    Args:
        llm: vLLM instance
        prompts: List of prompts
        branch_trigger_mode: random, entropy, or entropy_waad
        target_n: Exact number of final answer candidates per prompt
        branching_factor: Maximum branching factor for each split
        max_tree_depth: Max depth for tree
        entropy_threshold: Entropy threshold for branching
        tau_importance: Tau for importance sampling
        temperature: Sampling temperature
        top_p: Top-p sampling parameter
        top_k: Top-k sampling parameter
        max_tokens: Max tokens to generate

    Returns:
        Pair of generations and per-prompt candidate/source metadata
    """
    if branch_trigger_mode not in {"random", "entropy", "entropy_waad"}:
        raise ValueError(f"Unsupported branch trigger mode: {branch_trigger_mode!r}.")
    if target_n < 1:
        raise ValueError(f"target_n must be positive, got {target_n}.")
    if branch_trigger_mode == "entropy_waad" and tau_importance is None:
        raise ValueError("entropy_waad mode requires a numeric tau_importance.")

    tree_params = [
        SamplingParams(
            temperature=temperature,
            max_tokens=max_tokens,
            top_p=top_p,
            top_k=top_k,
            seed=(
                None if seed is None else seed + prompt_idx * target_n),
            tree_search_params=TreeSearchParams(
                enable_tree_search=True,
                entropy_threshold=entropy_threshold,
                branching_factor=branching_factor,
                max_tree_depth=max_tree_depth,
                tau_importance=(
                    tau_importance if branch_trigger_mode == "entropy_waad"
                    else None),
                min_seg_length=min_seg_length,
                branch_trigger_mode=branch_trigger_mode,
                random_branch_probability=random_branch_probability,
                max_num_leaves=target_n,
            ),
        )
        for prompt_idx in range(len(prompts))
    ]

    outputs = llm.generate(prompts, tree_params)
    if len(outputs) != len(prompts):
        raise RuntimeError(
            f"{branch_trigger_mode} tree returned {len(outputs)} prompt "
            f"outputs for {len(prompts)} prompts.")

    all_generations = []
    metadata = []
    filler_requests = []

    for prompt_idx, output in enumerate(outputs):
        leaf_generations, tree_shape = extract_tree_leaf_candidates(output)
        if len(leaf_generations) > target_n:
            raise RuntimeError(
                f"{branch_trigger_mode} tree prompt {prompt_idx} returned "
                f"{len(leaf_generations)} leaves, exceeding max_num_leaves="
                f"{target_n}. Verify that the patched vLLM is loaded.")

        all_generations.append(list(leaf_generations))
        needed = target_n - len(leaf_generations)
        prompt_metadata = {
            **tree_shape,
            "filler_count": needed,
            "total_count": len(leaf_generations),
            "candidate_sources": ["tree"] * len(leaf_generations),
        }
        metadata.append(prompt_metadata)
        if needed:
            filler_requests.append((prompt_idx, prompts[prompt_idx], needed))

    if filler_requests:
        total_missing = sum(needed for _, _, needed in filler_requests)
        print(
            f"  {branch_trigger_mode}: filling {total_missing} iid slots "
            f"across {len(filler_requests)} prompts...")
        filler_prompts = [prompt for _, prompt, _ in filler_requests]
        filler_params = []
        for prompt_idx, _, needed in filler_requests:
            filler_seed = (
                None if seed is None
                else seed + 1_000_003 + prompt_idx * target_n)
            filler_params.append(SamplingParams(
                temperature=temperature,
                max_tokens=max_tokens,
                n=needed,
                top_p=top_p,
                top_k=top_k,
                seed=filler_seed,
            ))

        filler_outputs = llm.generate(filler_prompts, filler_params)
        if len(filler_outputs) != len(filler_requests):
            raise RuntimeError(
                f"{branch_trigger_mode} filler returned {len(filler_outputs)} "
                f"prompt outputs for {len(filler_requests)} requests.")

        for filler_output, (prompt_idx, _, needed) in zip(
                filler_outputs, filler_requests):
            filler_texts = [
                completion.text if completion.text is not None else ""
                for completion in filler_output.outputs
            ]
            if len(filler_texts) != needed:
                raise RuntimeError(
                    f"{branch_trigger_mode} filler for prompt {prompt_idx} "
                    f"returned {len(filler_texts)} candidates; expected "
                    f"exactly {needed}.")
            all_generations[prompt_idx].extend(filler_texts)
            metadata[prompt_idx]["candidate_sources"].extend(
                ["grpo_filler"] * needed)
            metadata[prompt_idx]["total_count"] += needed

    for prompt_idx, (generations, prompt_metadata) in enumerate(
            zip(all_generations, metadata)):
        if len(generations) != target_n:
            raise RuntimeError(
                f"{branch_trigger_mode} prompt {prompt_idx} has "
                f"{len(generations)} final candidates; expected {target_n}.")
        if prompt_metadata["total_count"] != target_n:
            raise RuntimeError(
                f"{branch_trigger_mode} prompt {prompt_idx} metadata count "
                f"is {prompt_metadata['total_count']}; expected {target_n}.")

    return all_generations, metadata


# ========== Main Experiment ==========

def summarize_candidate_metadata(
    metadata: List[Dict[str, Any]],
) -> Dict[str, float]:
    """Summarize the budget composition for one generation method."""
    if not metadata:
        return {}

    summary = {}
    for key in (
        "tree_leaf_count",
        "tree_internal_node_count",
        "tree_output_node_count",
        "filler_count",
        "total_count",
    ):
        values = [float(item.get(key, 0)) for item in metadata]
        summary[f"{key}_mean"] = float(np.mean(values))
        summary[f"{key}_min"] = float(np.min(values))
        summary[f"{key}_max"] = float(np.max(values))
    return summary


def validate_experiment_args(args: argparse.Namespace) -> None:
    """Fail early on configurations that cannot define a fair comparison."""
    for flag, value in (
        ("--num-samples", args.num_samples),
        ("--max-tokens", args.max_tokens),
        ("--max-model-len", args.max_model_len),
        ("--tensor-parallel-size", args.tensor_parallel_size),
        ("--calibration-n", args.calibration_n),
        ("--calibration-max-tokens", args.calibration_max_tokens),
    ):
        if value < 1:
            raise ValueError(f"{flag} must be positive, got {value}.")
    if args.n < 1:
        raise ValueError(f"--n must be positive, got {args.n}.")
    if args.branching_factor < 2:
        raise ValueError(
            "--branching-factor must be at least 2 for tree decoding.")
    if args.max_tree_depth < 0:
        raise ValueError("--max-tree-depth must be non-negative.")
    if args.min_seg_length < 0:
        raise ValueError("--min-seg-length must be non-negative.")
    if not 0.0 <= args.random_branch_probability <= 1.0:
        raise ValueError("--random-branch-probability must be in [0, 1].")
    if not 0.0 <= args.calibration_quantile <= 1.0:
        raise ValueError("--calibration-quantile must be in [0, 1].")
    if not 0.0 < args.top_p <= 1.0:
        raise ValueError("--top-p must be in (0, 1].")
    if args.top_k < -1:
        raise ValueError("--top-k must be -1, 0, or a positive integer.")
    if not 0.0 < args.gpu_memory_utilization <= 1.0:
        raise ValueError("--gpu-memory-utilization must be in (0, 1].")
    for flag, value in (
        ("--temperature", args.temperature),
        ("--entropy-threshold", args.entropy_threshold),
        ("--tau-importance", args.tau_importance),
        ("--random-branch-probability", args.random_branch_probability),
        ("--calibration-quantile", args.calibration_quantile),
    ):
        if not math.isfinite(value):
            raise ValueError(f"{flag} must be finite, got {value}.")
    if args.temperature < 1e-5:
        raise ValueError(
            "--temperature must be at least 1e-5 because this experiment "
            "requires stochastic n-way sampling.")


def run_experiment(args):
    """Run the full comparison experiment."""
    run_id = uuid.uuid4().hex
    requested_num_samples = args.num_samples
    requested_max_tokens = args.max_tokens
    print("=" * 80)
    print("GRPO vs Random / Entropy / Entropy+WAAD Tree Decoding")
    print("=" * 80)

    if not VLLM_AVAILABLE:
        raise RuntimeError(
            f"Unable to import vLLM from {VLLM_SOURCE_PATH!r}: "
            f"{VLLM_IMPORT_ERROR}")
    required_tree_fields = {
        "branch_trigger_mode",
        "random_branch_probability",
        "max_num_leaves",
    }
    available_tree_fields = set(TreeSearchParams.__dataclass_fields__)
    missing_tree_fields = required_tree_fields - available_tree_fields
    if missing_tree_fields:
        raise RuntimeError(
            "The imported vLLM does not contain the comparison-only tree "
            f"extensions {sorted(missing_tree_fields)}. Imported module: "
            f"{vllm.__file__}")
    expected_vllm_root = Path(VLLM_SOURCE_PATH).resolve()
    imported_vllm_path = Path(vllm.__file__).resolve()
    try:
        imported_vllm_path.relative_to(expected_vllm_root)
    except ValueError as exc:
        raise RuntimeError(
            f"Requested vLLM checkout {expected_vllm_root} but imported "
            f"{imported_vllm_path}. Refusing to run against a fallback "
            "installation.") from exc
    print(f"vLLM source: {vllm.__file__}")

    # Check dataset path
    dataset_path = args.dataset_path
    if not os.path.exists(dataset_path):
        # Try to find from environment variable
        ray_data_home = os.environ.get('RAY_DATA_HOME', '')
        if ray_data_home:
            alt_path = os.path.join(ray_data_home, 'dapo-math-17k.parquet')
            if os.path.exists(alt_path):
                dataset_path = alt_path

    if not os.path.exists(dataset_path):
        raise FileNotFoundError(
            f"Dataset not found at {args.dataset_path}. "
            f"Please set RAY_DATA_HOME environment variable or provide correct path."
        )

    if args.quick_test:
        print("\n" + "="*80)
        print("QUICK TEST MODE ENABLED - Using only 5 samples, 256 max tokens")
        print("="*80)
        args.num_samples = min(args.num_samples, 5)
        args.max_tokens = 256

    print(f"\n1. Extracting {args.num_samples} unique queries from: {dataset_path}")
    print("   Using streaming mode - will stop when enough samples are collected")
    examples = extract_unique_queries_streaming(dataset_path, num_samples=args.num_samples)

    # Save examples for reference
    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    examples_file = output_dir / "sampled_examples.json"
    with open(examples_file, "w", encoding="utf-8") as f:
        json.dump([{
            'idx': ex.idx,
            'problem': ex.problem,
            'prompt': ex.prompt,
            'ground_truth': ex.ground_truth
        } for ex in examples], f, indent=2)
    print(f"   Saved sampled examples to: {examples_file}")

    # Initialize LLM
    print(f"\n2. Initializing vLLM with model: {args.model_path}")
    print("   This may take 5-15 minutes depending on model size...")
    print("   - You should see GPU memory being used via nvidia-smi")
    print("   - If you don't see progress for >20 minutes, something is wrong")
    sys.stdout.flush()

    try:
        llm = LLM(
            model=args.model_path,
            tensor_parallel_size=args.tensor_parallel_size,
            dtype=args.dtype,
            gpu_memory_utilization=args.gpu_memory_utilization,
            enforce_eager=True,
            max_model_len=args.max_model_len,
            seed=args.seed,
            # WAAD currently requires decode-only batches. This is local to
            # the comparison runner and does not alter the training pipeline.
            enable_chunked_prefill=False,
        )
        print("   ✓ vLLM initialized successfully!")
    except Exception as e:
        print(f"\n✗ Failed to initialize vLLM: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)
    sys.stdout.flush()

    prompts = [ex.prompt for ex in examples]
    ground_truths = [ex.ground_truth for ex in examples]
    calibration_prompt_count = 0

    # Calibrate thresholds if auto-calibration is enabled
    entropy_threshold = args.entropy_threshold
    tau_importance = args.tau_importance
    calibration_time = 0.0

    if args.auto_calibrate_thresholds:
        print(f"\n2.5. Auto-calibrating thresholds (using {args.calibration_quantile*100}th percentile)...")
        # Only use first 10 prompts for calibration to avoid hanging
        calibration_prompts = prompts[:10]
        calibration_prompt_count = len(calibration_prompts)
        print(f"  Using {len(calibration_prompts)} prompts for calibration")
        sys.stdout.flush()
        calibration_start = time.time()
        entropy_threshold, tau_importance = collect_threshold_stats(
            llm=llm,
            prompts=calibration_prompts,
            n=args.calibration_n,
            temperature=args.temperature,
            top_p=args.top_p,
            top_k=args.top_k,
            max_tokens=args.calibration_max_tokens,
            quantile=args.calibration_quantile,
            seed=args.seed,
        )
        calibration_time = time.time() - calibration_start
        print(f"\nCalibrated thresholds:")
        print(f"  entropy_threshold: {entropy_threshold:.4f}")
        print(f"  tau_importance:    {tau_importance:.4f}")

    method_generations: Dict[str, List[List[str]]] = {}
    method_results: Dict[str, List[List[bool]]] = {}
    method_metadata: Dict[str, List[Dict[str, Any]]] = {}
    method_summaries: Dict[str, Dict[str, Any]] = {}

    print(f"\n3. Generating with Base GRPO (n={args.n})...")
    start_time = time.time()
    base_generations = generate_base_grpo(
        llm=llm,
        prompts=prompts,
        n=args.n,
        temperature=args.temperature,
        top_p=args.top_p,
        top_k=args.top_k,
        max_tokens=args.max_tokens,
        seed=args.seed,
    )
    base_time = time.time() - start_time
    print(f"   Base GRPO time: {base_time:.2f}s")

    base_results = [
        evaluate_generations(generations, ground_truth)
        for generations, ground_truth in zip(base_generations, ground_truths)
    ]
    base_pass_k = compute_all_pass_k(base_results, max_k=args.n)
    base_metadata = [{
        "tree_leaf_count": 0,
        "tree_internal_node_count": 0,
        "tree_output_node_count": 0,
        "filler_count": 0,
        "total_count": args.n,
        "candidate_sources": ["grpo"] * args.n,
    } for _ in examples]
    method_generations["base_grpo"] = base_generations
    method_results["base_grpo"] = base_results
    method_metadata["base_grpo"] = base_metadata
    method_summaries["base_grpo"] = {
        "pass_k": base_pass_k,
        "time": base_time,
        "budget": summarize_candidate_metadata(base_metadata),
    }

    tree_specs = (
        ("random_tree", "random", None),
        ("entropy_only_tree", "entropy", None),
        ("entropy_waad_tree", "entropy_waad", tau_importance),
    )
    for method_idx, (method_key, trigger_mode, method_tau) in enumerate(
            tree_specs, start=4):
        label = METHOD_LABELS[method_key]
        mode_detail = (
            f"p={args.random_branch_probability:.3f}"
            if trigger_mode == "random"
            else f"entropy>{entropy_threshold:.4f}"
        )
        if trigger_mode == "entropy_waad":
            mode_detail += f", WAAD>{method_tau:.4f}"
        print(
            f"\n{method_idx}. Generating {label} ({mode_detail}, "
            f"B={args.branching_factor}, depth={args.max_tree_depth}, "
            f"candidate budget={args.n})...")

        start_time = time.time()
        generations, candidate_metadata = generate_tree_decoding(
            llm=llm,
            prompts=prompts,
            branch_trigger_mode=trigger_mode,
            target_n=args.n,
            branching_factor=args.branching_factor,
            max_tree_depth=args.max_tree_depth,
            entropy_threshold=entropy_threshold,
            tau_importance=method_tau,
            random_branch_probability=args.random_branch_probability,
            min_seg_length=args.min_seg_length,
            temperature=args.temperature,
            top_p=args.top_p,
            top_k=args.top_k,
            max_tokens=args.max_tokens,
            seed=args.seed,
        )
        elapsed = time.time() - start_time
        results = [
            evaluate_generations(candidates, ground_truth)
            for candidates, ground_truth in zip(generations, ground_truths)
        ]
        pass_k = compute_all_pass_k(results, max_k=args.n)
        budget = summarize_candidate_metadata(candidate_metadata)

        method_generations[method_key] = generations
        method_results[method_key] = results
        method_metadata[method_key] = candidate_metadata
        method_summaries[method_key] = {
            "pass_k": pass_k,
            "time": elapsed,
            "budget": budget,
        }
        print(
            f"   {label} time: {elapsed:.2f}s; mean tree leaves: "
            f"{budget['tree_leaf_count_mean']:.2f}; mean iid fillers: "
            f"{budget['filler_count_mean']:.2f}")

    # Save generations
    generations_file = output_dir / "generations.json"
    generations_data = {
        "schema_version": 2,
        "run_id": run_id,
        "candidate_budget_n": args.n,
        "pass_at_k_definition": "uniform_candidate_pool_combinatorial",
        'examples': [{
            'idx': ex.idx,
            'problem': ex.problem,
            'prompt': ex.prompt,
            'ground_truth': ex.ground_truth,
        } for ex in examples],
    }
    for method_key in METHOD_LABELS:
        generations_data[method_key] = {
            "generations": method_generations[method_key],
            "results": method_results[method_key],
            "candidate_metadata": method_metadata[method_key],
        }
    with open(generations_file, "w", encoding="utf-8") as f:
        json.dump(generations_data, f, indent=2)
    print(f"\nSaved generations to: {generations_file}")

    # Print comparison summary
    print("\n" + "=" * 80)
    print("COMPARISON SUMMARY")
    print("=" * 80)
    column_width = 22
    print(
        f"\n{'Metric':<12}"
        + "".join(
            f"{METHOD_LABELS[key]:<{column_width}}" for key in METHOD_LABELS))
    print("-" * (12 + column_width * len(METHOD_LABELS)))

    for k in range(1, args.n + 1):
        metric = f"pass@{k}"
        print(
            f"{metric:<12}"
            + "".join(
                f"{method_summaries[key]['pass_k'][metric]:<{column_width}.4f}"
                for key in METHOD_LABELS))
    print("-" * (12 + column_width * len(METHOD_LABELS)))
    print(
        f"{'Time (s)':<12}"
        + "".join(
            f"{method_summaries[key]['time']:<{column_width}.2f}"
            for key in METHOD_LABELS))

    # Save summary
    summary: Dict[str, Any] = {
        "schema_version": 2,
        "run_id": run_id,
        "pass_at_k_definition": "uniform_candidate_pool_combinatorial",
        'config': {
            'model': args.model_path,
            "dataset_path": dataset_path,
            "vllm_source_path": VLLM_SOURCE_PATH,
            "vllm_module": vllm.__file__,
            "requested_num_samples": requested_num_samples,
            'num_samples': len(examples),
            "quick_test": args.quick_test,
            "tensor_parallel_size": args.tensor_parallel_size,
            "dtype": args.dtype,
            "gpu_memory_utilization": args.gpu_memory_utilization,
            "max_model_len": args.max_model_len,
            'n': args.n,
            'branching_factor': args.branching_factor,
            'max_tree_depth': args.max_tree_depth,
            "min_seg_length": args.min_seg_length,
            'entropy_threshold': entropy_threshold,
            'tau_importance': tau_importance,
            "random_branch_probability": args.random_branch_probability,
            'auto_calibrate_thresholds': args.auto_calibrate_thresholds,
            "calibration_n": args.calibration_n,
            "calibration_max_tokens": args.calibration_max_tokens,
            "calibration_prompt_count": calibration_prompt_count,
            "calibration_quantile": args.calibration_quantile,
            "calibration_time": calibration_time,
            'temperature': args.temperature,
            'top_p': args.top_p,
            'top_k': args.top_k,
            'max_tokens': args.max_tokens,
            "requested_max_tokens": requested_max_tokens,
            "seed": args.seed,
            "candidate_budget_definition": (
                "complete_tree_leaves_plus_iid_fillers_equals_n"),
        }
    }
    summary.update(method_summaries)

    summary_file = output_dir / "results_summary.json"
    with open(summary_file, "w", encoding="utf-8") as f:
        json.dump(summary, f, indent=2)
    print(f"\nSaved results summary to: {summary_file}")

    # Also save as CSV for easier analysis
    csv_data = []
    for k in range(1, args.n + 1):
        row = {"k": k}
        metric = f"pass@{k}"
        for method_key in METHOD_LABELS:
            row[method_key] = method_summaries[method_key]["pass_k"][metric]
            if method_key != "base_grpo":
                row[f"{method_key}_minus_base"] = (
                    row[method_key] - row["base_grpo"])
        csv_data.append(row)
    csv_file = output_dir / "results_summary.csv"
    pd.DataFrame(csv_data).to_csv(csv_file, index=False)
    print(f"Saved CSV summary to: {csv_file}")

    print("\n" + "=" * 80)
    print("Experiment complete!")
    print("=" * 80)

    return summary


def main():
    parser = argparse.ArgumentParser(
        description="Tree Decoding vs Base GRPO Comparison Experiment"
    )

    # Dataset
    parser.add_argument(
        "--dataset-path",
        type=str,
        default="${RAY_DATA_HOME}/data/dapo-math-17k.parquet",
        help="Path to dapo-math dataset"
    )
    parser.add_argument(
        "--num-samples",
        type=int,
        default=500,
        help="Number of unique queries to sample"
    )
    parser.add_argument(
        "--quick-test",
        action="store_true",
        help="Run a quick test with only 5 samples and shorter generation"
    )

    # Model
    parser.add_argument(
        "--model-path",
        type=str,
        required=True,
        help="Path to model checkpoint"
    )
    parser.add_argument(
        "--tensor-parallel-size",
        type=int,
        default=1,
        help="Tensor parallel size"
    )
    parser.add_argument(
        "--dtype",
        type=str,
        default="float16",
        help="Data type"
    )
    parser.add_argument(
        "--gpu-memory-utilization",
        type=float,
        default=0.9,
        help="GPU memory utilization"
    )
    parser.add_argument(
        "--max-model-len",
        type=int,
        default=4096,
        help="Max model length"
    )

    # Sampling
    parser.add_argument(
        "--n",
        type=int,
        default=8,
        help="Number of sequences per prompt (total sequences per query)"
    )
    parser.add_argument(
        "--temperature",
        type=float,
        default=1.0,
        help="Sampling temperature (verl default: 1.0)"
    )
    parser.add_argument(
        "--top-p",
        type=float,
        default=1.0,
        help="Top-p sampling parameter (verl default: 1.0)"
    )
    parser.add_argument(
        "--top-k",
        type=int,
        default=-1,
        help="Top-k sampling parameter (verl default: -1)"
    )
    parser.add_argument(
        "--max-tokens",
        type=int,
        default=4096,
        help="Max tokens to generate"
    )
    parser.add_argument(
        "--seed",
        type=int,
        default=42,
        help="Seed for model sampling and the random branch trigger"
    )

    # Tree Decoding
    parser.add_argument(
        "--branching-factor",
        type=int,
        default=2,
        help="Tree branching factor (verl default: 2)"
    )
    parser.add_argument(
        "--max-tree-depth",
        type=int,
        default=3,
        help="Max tree depth (verl default: 3)"
    )
    parser.add_argument(
        "--min-seg-length",
        type=int,
        default=128,
        help="Minimum generated segment length before a split is eligible"
    )
    parser.add_argument(
        "--entropy-threshold",
        type=float,
        default=1.0,
        help="Entropy threshold for branching (verl default: 1.0)"
    )
    parser.add_argument(
        "--tau-importance",
        type=float,
        default=0.0,
        help="WAAD threshold when auto-calibration is disabled"
    )
    parser.add_argument(
        "--random-branch-probability",
        type=float,
        default=0.2,
        help="Per-eligible-token split probability for random tree"
    )

    # Threshold Auto-calibration
    parser.add_argument(
        "--auto-calibrate-thresholds",
        action="store_true",
        help="Auto-calibrate entropy_threshold and tau_importance using collect_threshold_stats mode"
    )
    parser.add_argument(
        "--calibration-n",
        type=int,
        default=5,
        help="Number of sequences per prompt for threshold calibration"
    )
    parser.add_argument(
        "--calibration-max-tokens",
        type=int,
        default=200,
        help="Max tokens for threshold calibration (shorter than full generation)"
    )
    parser.add_argument(
        "--calibration-quantile",
        type=float,
        default=0.8,
        help="Quantile to use for threshold (0.8 = 80th percentile)"
    )

    # Output
    parser.add_argument(
        "--output-dir",
        type=str,
        default="./tree_decoding_results",
        help="Output directory"
    )

    args = parser.parse_args()
    validate_experiment_args(args)

    # Expand environment variables in path
    if '${RAY_DATA_HOME}' in args.dataset_path:
        ray_data_home = os.environ.get('RAY_DATA_HOME', '')
        args.dataset_path = args.dataset_path.replace('${RAY_DATA_HOME}', ray_data_home)

    run_experiment(args)


if __name__ == "__main__":
    main()
